### ISSUE TITLE
Needs local usage instructions

### ISSUE THREAD

**Issue by mpelzsherman** [rentpath/eslint-config-rentpath#12]
I've installed the module per instructions, but when I run `eslint .` I get:

<pre>
Error: Cannot read config package: eslint-config-rentpath
Error: Cannot find module 'eslint-config-rentpath'
Referenced from: /Users/mpelzsherman/source/m.apartmentguide/.eslintrc
</pre>

**Comment by colinrymer** [comment]
Do the instructions at https://github.com/rentpath/eslint-config-rentpath/blob/master/README.md#installation and https://github.com/rentpath/eslint-config-rentpath/blob/master/README.md#usage not address this issue?

**Comment by Teapane** [comment]
I added a piece on adding a script to `package.json` as well.

**Comment by mpelzsherman** [comment]
They do now. :smile:. For some reason running the `eslint` command directly does not work, but `npm run lint` does. Thanks @Teapane.

**Comment by Teapane** [comment]
Of course! :dancer:
