### ISSUE TITLE
Error when running locally

### ISSUE THREAD

**Issue by mpelzsherman** [rentpath/eslint-config-rentpath#13]
I followed [these instructions](http://eslint.org/docs/developer-guide/shareable-configs) for using `npm link` to use the shared config, since it apparently hasn't been published to the global npm repository (?).

Getting the following error. Am I running it correctly?

<pre>
$ eslint .
/Users/mpelzsherman/source/eslint-config-rentpath/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].acceptTranspilerName" has additional properties.

Referenced from: /Users/mpelzsherman/source/eslint-config-rentpath/node_modules/eslint-config-airbnb/index.js
Referenced from: rentpath
Referenced from: /Users/mpelzsherman/source/m.apartmentguide/.eslintrc
Error: /Users/mpelzsherman/source/eslint-config-rentpath/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].acceptTranspilerName" has additional properties.
</pre>

**Comment by Teapane** [comment]
What do you mean it hasn't been published to NPM? https://www.npmjs.com/package/eslint-config-rentpath

**Comment by mpelzsherman** [comment]
Sorry - I assumed that's why I wasn't able to use it locally, per #12. I'll close this issue and seek assistance on slack for running locally.

**Comment by Teapane** [comment]
No problem. :smiley:

**Comment by colinrymer** [comment]
@mpelzsherman It looks like your issue is you're trying to lint everything, including your `node_modules` directory, which shouldn't be included in the linting process.

**Comment by colinrymer** [comment]
Actually, scratch what I just said.
