### ISSUE TITLE
Add react lint

### ISSUE THREAD

**Issue by Teapane** [rentpath/eslint-config-rentpath#3]
https://www.npmjs.com/package/eslint-plugin-react

**Comment by colinrymer** [comment]
Doesn't index.js#L3 need to be modified for react to be added?

**Comment by colinrymer** [comment]
See https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1 vs https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnbbase

**Comment by Teapane** [comment]
I'll take a look @colinrymer, thanks.

**Comment by Teapane** [comment]
Done
